<?php
/**
 * Steppa Discover — Curated Game Data Seeder
 */

return [
    [
        'title' => 'PUBG MOBILE',
        'slug' => 'pubg-mobile',
        'package_id' => 'com.tencent.ig',
        'genres' => ['Action', 'Battle Royale', 'Multiplayer'],
        'developer' => 'Level Infinite',
        'rating' => 4.4,
        'reviews' => '45M',
        'installs' => '500M+',
        'installs_raw' => 500000000,
        'size' => '800MB',
        'version' => '3.1.0',
        'updated' => 'April 2024',
        'price' => 'Free',
        'is_offline' => false,
        'icon' => 'https://play-lh.googleusercontent.com/JRd05pyBH41qjgsR-4rmHJnOLZdAFXtZjjL8TKWjHjFq_Mf5qlMm_oZ4yYg8Cqjm8M',
        'screenshots' => [
            'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=800&q=80',
            'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=800&q=80'
        ],
        'playstore_url' => 'https://play.google.com/store/apps/details?id=com.tencent.ig',
        'desc' => 'Experience the original battle royale mobile game that defined a genre. PUBG MOBILE delivers intense multiplayer combat where 100 players drop onto a massive island with one goal: survive. Loot weapons, drive vehicles, and outsmart your enemies in a shrinking play zone. With stunning HD graphics, smooth controls, and highly customizable layouts, it brings a console-quality shooter experience right to your Android device.',
        'trending_score' => 98,
        'featured' => true,
    ],
    [
        'title' => 'Subway Surfers',
        'slug' => 'subway-surfers',
        'package_id' => 'com.kiloo.subwaysurf',
        'genres' => ['Arcade', 'Offline', 'Casual'],
        'developer' => 'SYBO Games',
        'rating' => 4.6,
        'reviews' => '40M',
        'installs' => '1B+',
        'installs_raw' => 1000000000,
        'size' => '150MB',
        'version' => '3.25.0',
        'updated' => 'May 2024',
        'price' => 'Free',
        'is_offline' => true,
        'icon' => 'https://play-lh.googleusercontent.com/aFWiT2lTa9CYBpyPjfgfNmdzZKX3-lJK3AwhEjFd4iMPiA0eTU0_Q5Yh_GkdUVgW9F',
        'screenshots' => [
            'https://images.unsplash.com/photo-1511447333015-45b65e60f6d5?auto=format&fit=crop&w=800&q=80',
            'https://images.unsplash.com/photo-1551893665-f843f600794e?auto=format&fit=crop&w=800&q=80'
        ],
        'playstore_url' => 'https://play.google.com/store/apps/details?id=com.kiloo.subwaysurf',
        'desc' => 'DASH as fast as you can! DODGE the oncoming trains! Join Jake, Tricky, and Fresh as they escape from the grumpy Inspector and his dog in this classic endless runner. Subway Surfers boasts vibrant, colorful HD graphics, lightning-fast swipe acrobatics, and hoverboard surfing. It’s a timeless arcade hit that remains incredibly addictive and enjoyable completely offline.',
        'trending_score' => 95,
        'featured' => true,
    ],
    [
        'title' => 'Genshin Impact',
        'slug' => 'genshin-impact',
        'package_id' => 'com.miHoYo.GenshinImpact',
        'genres' => ['RPG', 'Adventure', 'Open World'],
        'developer' => 'COGNOSPHERE PTE. LTD.',
        'rating' => 4.3,
        'reviews' => '5M',
        'installs' => '50M+',
        'installs_raw' => 50000000,
        'size' => '1GB',
        'version' => '4.5.0',
        'updated' => 'March 2024',
        'price' => 'Free',
        'is_offline' => false,
        'icon' => 'https://play-lh.googleusercontent.com/JUaHX-0kBHGMhilDJ2P6lfpJwGpAhXTuNHWlpbGwcfSHKhzOdOdE6OMUVJ0hDalH_A',
        'screenshots' => [
            'https://images.unsplash.com/photo-1551103782-8ab4ad1c2a7b?auto=format&fit=crop&w=800&q=80',
            'https://images.unsplash.com/photo-1548686096-a4db9f2b9c6f?auto=format&fit=crop&w=800&q=80'
        ],
        'playstore_url' => 'https://play.google.com/store/apps/details?id=com.miHoYo.GenshinImpact',
        'desc' => 'Step into Teyvat, a vast open-world teeming with life and flowing with elemental energy. Genshin Impact is a breathtaking action RPG featuring stunning anime-style visuals, a deep elemental combat system, and a captivating storyline. Explore diverse nations, unlock dozens of unique characters, and conquer challenging dungeons in this genre-defining mobile masterpiece.',
        'trending_score' => 99,
        'featured' => true,
    ],
    [
        'title' => 'Candy Crush Saga',
        'slug' => 'candy-crush-saga',
        'package_id' => 'com.king.candycrushsaga',
        'genres' => ['Puzzle', 'Casual', 'Offline'],
        'developer' => 'King',
        'rating' => 4.6,
        'reviews' => '35M',
        'installs' => '1B+',
        'installs_raw' => 1000000000,
        'size' => '90MB',
        'version' => '1.272.0',
        'updated' => 'April 2024',
        'price' => 'Free',
        'is_offline' => true,
        'icon' => 'https://play-lh.googleusercontent.com/DJh_0b8U9kpDrR14rXCHqAXlOdJmJvH-OvLbA2jQ9TT3BrNsPz9UeD-Lkm-UiGCb0A',
        'screenshots' => [
            'https://images.unsplash.com/photo-1606092195730-5d7b9af1efc5?auto=format&fit=crop&w=800&q=80'
        ],
        'playstore_url' => 'https://play.google.com/store/apps/details?id=com.king.candycrushsaga',
        'desc' => 'Master the legendary match-3 puzzle game from King! With over a trillion matching levels played, Candy Crush Saga is one of the most popular mobile games of all time. Match, pop, and blast candies in this tasty puzzle adventure to progress to the next level and get a sugar rush!',
        'trending_score' => 90,
        'featured' => false,
    ],
    [
        'title' => 'Clash of Clans',
        'slug' => 'clash-of-clans',
        'package_id' => 'com.supercell.clashofclans',
        'genres' => ['Strategy', 'Multiplayer'],
        'developer' => 'Supercell',
        'rating' => 4.5,
        'reviews' => '60M',
        'installs' => '500M+',
        'installs_raw' => 500000000,
        'size' => '250MB',
        'version' => '16.100.4',
        'updated' => 'February 2024',
        'price' => 'Free',
        'is_offline' => false,
        'icon' => 'https://play-lh.googleusercontent.com/LBB2JfwMJPvDQ9wMqk0LGZ1L16MRH4VsovXyZ1mRnf6pRh6vMtBxJp3h0K6S8bDhPg',
        'screenshots' => [
            'https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?auto=format&fit=crop&w=800&q=80'
        ],
        'playstore_url' => 'https://play.google.com/store/apps/details?id=com.supercell.clashofclans',
        'desc' => 'Join millions of players worldwide as you build your village, raise a clan, and compete in epic Clan Wars! Clash of Clans is the ultimate mobile strategy game. Defend your base with cannons, bombs, and walls while training an army of Barbarians, Archers, and Dragons to raid other players for resources.',
        'trending_score' => 88,
        'featured' => false,
    ],
    [
        'title' => 'Roblox',
        'slug' => 'roblox',
        'package_id' => 'com.roblox.client',
        'genres' => ['Simulation', 'Multiplayer', 'Adventure'],
        'developer' => 'Roblox Corporation',
        'rating' => 4.4,
        'reviews' => '30M',
        'installs' => '500M+',
        'installs_raw' => 500000000,
        'size' => '170MB',
        'version' => '2.617.433',
        'updated' => 'April 2024',
        'price' => 'Free',
        'is_offline' => false,
        'icon' => 'https://play-lh.googleusercontent.com/oBZgVH9nT4kB2CjTSxCGW1UNJL3uG0_qI4JjMEGzMQODHpJmGJnFqtHMaEJnAuR4bQ',
        'screenshots' => [
            'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=800&q=80'
        ],
        'playstore_url' => 'https://play.google.com/store/apps/details?id=com.roblox.client',
        'desc' => 'Roblox is the ultimate virtual universe that lets you create, share experiences with friends, and be anything you can imagine. Join millions of people and discover an infinite variety of immersive experiences created by a global community!',
        'trending_score' => 97,
        'featured' => true,
    ],
    [
        'title' => 'Asphalt 9: Legends',
        'slug' => 'asphalt-9-legends',
        'package_id' => 'com.gameloft.android.ANMP.GloftA9HM',
        'genres' => ['Racing', 'Action', 'Multiplayer'],
        'developer' => 'Gameloft SE',
        'rating' => 4.5,
        'reviews' => '7M',
        'installs' => '100M+',
        'installs_raw' => 100000000,
        'size' => '2.5GB',
        'version' => '4.3.0',
        'updated' => 'March 2024',
        'price' => 'Free',
        'is_offline' => false,
        'icon' => 'https://ui-avatars.com/api/?name=Asphalt+9&background=3b82f6&color=fff&size=256&bold=true',
        'screenshots' => [
            'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80'
        ],
        'playstore_url' => 'https://play.google.com/store/apps/details?id=com.gameloft.android.ANMP.GloftA9HM',
        'desc' => 'Tear up the asphalt in the ultimate arcade racing experience. Asphalt 9: Legends features a top roster of real hypercars from renowned manufacturers like Ferrari, Porsche, Lamborghini, and W Motors. Push your limits in breathtaking locations around the globe and prove you’re the best driver in multiplayer.',
        'trending_score' => 85,
        'featured' => false,
    ],
    [
        'title' => 'EA SPORTS FC MOBILE 24',
        'slug' => 'ea-sports-fc-mobile',
        'package_id' => 'com.ea.gp.fifamobile',
        'genres' => ['Sports', 'Simulation', 'Multiplayer'],
        'developer' => 'ELECTRONIC ARTS',
        'rating' => 4.3,
        'reviews' => '10M',
        'installs' => '100M+',
        'installs_raw' => 100000000,
        'size' => '400MB',
        'version' => '21.0.03',
        'updated' => 'April 2024',
        'price' => 'Free',
        'is_offline' => false,
        'icon' => 'https://ui-avatars.com/api/?name=FC+Mobile&background=10b981&color=fff&size=256&bold=true',
        'screenshots' => [
            'https://images.unsplash.com/photo-1546519638-68955109ae36?auto=format&fit=crop&w=800&q=80'
        ],
        'playstore_url' => 'https://play.google.com/store/apps/details?id=com.ea.gp.fifamobile',
        'desc' => 'The beautiful game is here! Build your Ultimate Team with soccer stars from the top leagues, including the Premier League, LALIGA, and Bundesliga. EA SPORTS FC Mobile delivers highly authentic soccer action, real-time 11v11 matches, and deep tactical management directly on your phone.',
        'trending_score' => 92,
        'featured' => true,
    ],
    [
        'title' => 'Minecraft',
        'slug' => 'minecraft',
        'package_id' => 'com.mojang.minecraftpe',
        'genres' => ['Arcade', 'Simulation', 'Adventure'],
        'developer' => 'Mojang',
        'rating' => 4.5,
        'reviews' => '5M',
        'installs' => '50M+',
        'installs_raw' => 50000000,
        'size' => '150MB',
        'version' => '1.20.73',
        'updated' => 'April 2024',
        'price' => '$6.99',
        'is_offline' => true,
        'icon' => 'https://play-lh.googleusercontent.com/VSwHkBFGr2P2KJNfTbOBPpd5cqUkfHiXJKqFJDvIHfFtG_4s4W_MQeM8gN4N7oJwPw',
        'screenshots' => [
            'https://images.unsplash.com/photo-1535223289429-72aad1c31055?auto=format&fit=crop&w=800&q=80'
        ],
        'playstore_url' => 'https://play.google.com/store/apps/details?id=com.mojang.minecraftpe',
        'desc' => 'Explore infinite worlds and build everything from the simplest of homes to the grandest of castles. Play in creative mode with unlimited resources or mine deep into the world in survival mode, crafting weapons and armor to fend off dangerous mobs. Minecraft is the ultimate sandbox block-building game.',
        'trending_score' => 94,
        'featured' => true,
    ],
    [
        'title' => 'Stardew Valley',
        'slug' => 'stardew-valley',
        'package_id' => 'com.chucklefish.stardewvalley',
        'genres' => ['Simulation', 'RPG', 'Offline'],
        'developer' => 'ConcernedApe',
        'rating' => 4.7,
        'reviews' => '150K',
        'installs' => '1M+',
        'installs_raw' => 1000000,
        'size' => '350MB',
        'version' => '1.5.6',
        'updated' => 'January 2024',
        'price' => '$4.99',
        'is_offline' => true,
        'icon' => 'https://ui-avatars.com/api/?name=Stardew+Valley&background=14b8a6&color=fff&size=256&bold=true',
        'screenshots' => [
            'https://images.unsplash.com/photo-1511447333015-45b65e60f6d5?auto=format&fit=crop&w=800&q=80'
        ],
        'playstore_url' => 'https://play.google.com/store/apps/details?id=com.chucklefish.stardewvalley',
        'desc' => 'Move to the country and cultivate a new life in this award-winning open-ended farming RPG! With over 50+ hours of gameplay, Stardew Valley offers a rich, incredibly detailed world. Farm, fish, forage, mine, and build relationships with the colorful inhabitants of Pelican Town.',
        'trending_score' => 82,
        'featured' => false,
    ],
    [
        'title' => 'Among Us',
        'slug' => 'among-us',
        'package_id' => 'com.innersloth.spacemafia',
        'genres' => ['Casual', 'Action', 'Multiplayer'],
        'developer' => 'Innersloth LLC',
        'rating' => 4.1,
        'reviews' => '13M',
        'installs' => '500M+',
        'installs_raw' => 500000000,
        'size' => '130MB',
        'version' => '2024.3.5',
        'updated' => 'March 2024',
        'price' => 'Free',
        'is_offline' => false,
        'icon' => 'https://play-lh.googleusercontent.com/CDsvE3N2aTT6B9MsTm4g5KJJbIiUQ4cpQoNLYzGWG8pzibU7JFDScDnjYbAEH7rh_Q',
        'screenshots' => [
            'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=800&q=80'
        ],
        'playstore_url' => 'https://play.google.com/store/apps/details?id=com.innersloth.spacemafia',
        'desc' => 'Play online or over local WiFi with 4-15 players as you attempt to prep your spaceship for departure, but beware as one or more random players among the Crew are Impostors bent on killing everyone! A fantastic party game built on deception, deduction, and chaos.',
        'trending_score' => 89,
        'featured' => false,
    ],
    [
        'title' => 'Duolingo: Language Lessons',
        'slug' => 'duolingo',
        'package_id' => 'com.duolingo',
        'genres' => ['Educational', 'Casual'],
        'developer' => 'Duolingo',
        'rating' => 4.7,
        'reviews' => '20M',
        'installs' => '100M+',
        'installs_raw' => 100000000,
        'size' => '60MB',
        'version' => '5.145.5',
        'updated' => 'April 2024',
        'price' => 'Free',
        'is_offline' => true,
        'icon' => 'https://ui-avatars.com/api/?name=Duolingo&background=06b6d4&color=fff&size=256&bold=true',
        'screenshots' => [
            'https://images.unsplash.com/photo-1511447333015-45b65e60f6d5?auto=format&fit=crop&w=800&q=80'
        ],
        'playstore_url' => 'https://play.google.com/store/apps/details?id=com.duolingo',
        'desc' => 'Learn a new language with the world’s most-downloaded education app! Duolingo is the fun, free app for learning 40+ languages through quick, bite-sized lessons. Practice speaking, reading, listening, and writing to build your vocabulary and grammar skills.',
        'trending_score' => 78,
        'featured' => false,
    ]
];
